### ISSUE TITLE
No video signal with webcam software

### ISSUE THREAD

**Issue by BOFH2k** [yoshimoto/gspca-kinect2#10]
Even with the fix for the probing issue #7  (and after adding the CFLAG from #6, fixing the Makefile and properly inserting the modules) with kernel 5.4.0-33-generic in Ubuntu 20.04 the Kinect v2 cannot be used as a webcam with software like cheese or via web browser: The webcam device is either not detected at all (cheese) or it can be activated in the web client (e.g. MS Teams) but only produces black video input.

Using ffmpeg to record input works, in contrast, but only with low VGA resolution:
`$ ffmpeg  -framerate 30 -video_size 640x480 -i /dev/video0  test.avi`  

This might point to an issue with obtaining the full HD data stream from the sensor?

**Comment by grandchild** [comment]
No this is an issue with the codec that's used. Kinect2 outputs MotionJPEG. Many apps cannot read that. I use a mediocre workaround described [here](https://github.com/yoshimoto/gspca-kinect2/pull/8#issuecomment-642292281).

**Comment by BOFH2k** [comment]
Ah, thanks for the explanation - your workaround from #8 does indeed work (in MS Teams at least, while cheese still won't identify a webcam), roughly utilizing 1 CPU core for 720p.

**Comment by BOFH2k** [comment]
Here's a command [script](https://github.com/yoshimoto/gspca-kinect2/files/4776041/v4l2lb.txt) for setting up the v4l2loopback device and starting the mjpeg conversion via ffmpeg.
