### ISSUE TITLE
Use as Webcam

### ISSUE THREAD

**Issue by SterlingButters** [yoshimoto/gspca-kinect2#11]
Anyone had any luck using this for kinect webcam? 

VLC displays video from the device just fine and web browser can detect the device but no video comes through.

**Comment by grandchild** [comment]
See my comment towards the end of #8, and if you have a newer kernel consider using my fork.

**Comment by SterlingButters** [comment]
@grandchild Lol nice - I did this just before reading your comment using https://github.com/umlaeute/v4l2loopback
